# Generated by Django 2.2.12 on 2020-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_group_memberships',
            field=models.BooleanField(default=False, help_text='Share group membership with other members'),
        ),
    ]
