# Generated by Django 2.2.12 on 2020-06-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_share_group_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='share_resolution',
            field=models.IntegerField(choices=[(5, 'Exact Location'), (2, 'Nearby location (±5km or 3 miles)'), (1, 'Neighborhood (±50km or 31 miles'), (0, 'Region (±500km or 310 miles')], default=1, help_text='Amount of resolution to apply to address.'),
        ),
    ]
